spring.application.name=alumnos
server.address=0.0.0.0
server.port=${PORT:5432}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false